baseURL = "https://stargazer1995.github.io/"

# Change the default theme to be use when building the site with Hugo
# theme = 'ananke'

# website title
# title = "StarGazer"

# language code ["en", "zh-CN", "fr", "pl", ...]
languageCode = "en-us"

